					<header>
						<h2 class="mainpageh2">Een bladzijde uit mijn dagboek...</h2>
					</header>

					<footer>
						<p class="post-info">DwaneWeb - 2021</p>
					</footer> 


			<div class="mainheader2">
		<a href="IMAGES/dagboekvergroot.jpg"  border="0" target="_blank" title="Een bladzijde uit mijn dagboek.">
			<img src="IMAGES/dagboek.jpg" border="0" target="_blank" title="Een bladzijde uit mijn dagboek."></a>
			
			</div>