
					<header>
						<h2 class="mainpageh2">Opdrachten</h2>
					</header>

					<footer>
						<p class="post-info">DwaneWeb - 2021</p>
					</footer> 
				<div class="mainheader2">
		<a href="IMAGES/opdracht1vergroot.jpg"  border="0" target="_blank" title="Opdracht: AND-poort (EN)">
			<img src="IMAGES/opdracht1.jpg" border="0" target="_blank" title="Opdracht: AND-poort (EN)"></a>
				</div>