					<header>
						<h2 class="mainpageh2">Informatie over mij:</h2>
					</header>

					<footer>
						<p class="post-info">DwaneWeb - 2021</p>
					</footer>

					<table border="10px" cellspacing="0" cellpadding="5"> 
						<tbody>
						<tr>
							<th>Vraag</th>
							<th>Antwoord</th>
						</tr>
			
						<tr>
							<td><b>Naam</b></td>
							<td>Dwane</td>
						</tr>
			
						<tr>
							<td><b>Achternaam</b></td>
							<td>Croc</td>
						</tr>
						
						<tr>
							<td><b>Geboortedatum</b></td>
							<td>11 November, 1997</td>
						</tr>
						
						<tr>
							<td><b>Geboorteplaats</b></td>
							<td>Amsterdam</td>
						</tr>
						
						<tr>
							<td><b>Afdeling</b></td>
							<td>Havo 4</td>
						</tr>
						
						<tr>
							<td><b>Look-a-like</b></td>
							<td>
								<div class="mainheader2">
									 <a href="IMAGES/210778vergroot.jpg" border="0" target="_blank" title="Picture of me, Dwane Croc">
									 <img src="IMAGES/210778.jpg" border="0" target="_blank" title="Picture of me, Dwane Croc">
									 </a>
								</div>
							</td>
						</tr>
					
						<tr>
							<td><b>Hobby</b></td>
							<td>Ik hou erg veel van voetballen, tennissen en basketballen</td>
						</tr>
						
						<tr>
							<td><b>Sport</b></td>
							<td>Voetballen en Tennissen</td>
						</tr>
								
						<tr>
							<td><b>Wat weet ik van informatica?</b></td>
							<td>Ik weet al welke en wat voor soorten programmeertalen er zijn en waarvoor je het gebruikt.<br>
								Ik heb nu ook geleerd wat binaire getallen zijn, in het vak informatica.<br>
								Dat computers met enen en nullen werken.
							</td>
						</tr>
			
						<tr>
							<td><b>Wat ik nog wil leren bij informatica</b></td>
							<td>Kennis ontwikkelen voor programmeertalen</td>
						</tr>
			
						<tr>
							<td><b>Interessante vakken</b></td>
							<td>Natuurkunde, Informatica en Scheikunde</td>
						</tr>
						
						<tr>
							<td><b>Studiekeuze</b></td>
							<td>HBO ICT</td>
						</tr>
						
						<tr>
							<td><b>Hogeschool</b></td>
							<td><a href="https://www.zuyd.nl/" target="_blank">Hogeschool Zuyd - Heerlen</a></td>
						</tr>
						
						<tr>
							<td><b>Lievelings huisdier</b></td>
							<td>Katten</td>
						</tr>
						
						<tr>
							<td><b>Lievelings voetbalclub</b></td>
							<td><a href="https://nl.wikipedia.org/wiki/FC_Barcelona" target="_blank">FC Barcelona</a></td>
						</tr>
						
						<tr>
							<td><b>Lievelings bands</b></td>
							<td>
								<ul>
									<li><a href="https://nl.wikipedia.org/wiki/Three_Days_Grace" target="_blank">Three Days Grace</a></li>
									<li><a href="https://nl.wikipedia.org/wiki/Thousand_Foot_Krutch" target="_blank">Thousand Foot Krutch</a></li>
								</ul>
							</td>
						</tr>
						
						<tr>
							<td><b>Lievelings kleur</b></td>
							<td>Blauw</td>
						</tr>
						
						<tr>
							<td><b>Top 5 lievelings liedje</b></td>
							<td>
								<ol>
									<li><a href="https://www.youtube.com/watch?v=lL2ZwXj1tXM" target="_blank">Three Days Grace - Never Too Late</a></li>
									<li><a href="https://www.youtube.com/watch?v=U8ai37gFvMk" target="_blank">Three Days Grace - Painkiller</a></li>
									<li><a href="https://www.youtube.com/watch?v=05wXNKzOkRM" target="_blank">Three Days Grace - Time of Dying</a></li>
									<li><a href="https://www.youtube.com/watch?v=TyUQiNmNug0" target="_blank">AshesRemainvideos - On My Own</a></li>
									<li><a href="https://www.youtube.com/watch?v=ocpDEOXABWg" target="_blank">Thousand Foot Krutch  - Courtesy Call</a></li>
								</ol>
							</td>
						</tr>
						
						<tr>
							<td><b>Lievelings getallen</b></td>
							<td>4 en 7</td>
						</tr>
						
						<tr>
							<td><b>Leukste pretpark / atractiepark</b></td>
							<td>Mijn favorite actractiepark is: <a href="https://www.efteling.com/nl" target="_blank">De Efteling</a><br>
								Mijn favorite actractie is: <a href="https://www.efteling.com/en/park/attractions/baron-1898" target="_blank">De Baron</a>
							</td>
						</tbody>
					</table>